### ISSUE TITLE
Merges fom 29.5. not working with build-essential package?

### ISSUE THREAD

**Issue by cwenzelg** [kjdev/php-ext-snappy#11]
Hi,

we are running snappy with build-essential installed on ubuntu:16.04 for some while now. This setup is not working anymore with the new merges from yesterday (29.05.).

We get the following error:
```
#error This file requires compiler and library support \
Step #0: /usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
```

What do we need to change? do we need more than the build-essential package? Can we provide more information on that issue?

Kind regards,
Christian

**Comment by kjdev** [comment]
Try building with `-std=c++1` in CXXFLAGS.

``` sh
$ export CXXFLAGS=-std=c++11
$ phpize
$ ./configure
$ make
```

**Comment by cwenzelg** [comment]
That worked, on Ubuntu, with docker, we install the build-essential package and run:

RUN git clone --recursive --depth=1 https://github.com/kjdev/php-ext-snappy.git
RUN cd php-ext-snappy \
    && export CXXFLAGS=-std=c++11 \
    && phpize \
    && ./configure \
    && make \
    && make install

I added a pull request to get that part into the readme as well.

Thanks for the fast help.
