### ISSUE TITLE
APCu serialization support

### ISSUE THREAD

**Issue by andypost** [kjdev/php-ext-snappy#16]
Would be great to allow build it with apcu support (like igbinary doing) to allow use snappy as serialization for it

**Comment by kjdev** [comment]
Created a serializer for APCu in Snappy that incorporates PHP serialization and compression/decompression.

Does it match what you expect?

**Comment by andypost** [comment]
@kjdev thank you a lot! I did testing and getting following numbers for fresh Drupal

`apc.serializer` php vs snappy vs igbinary - performance mostly the same (no viable ups and downs) 
But comparing memory usage got snappy is a leader 
php - 1.1MB
snappy - 643KB
igbinary - 862KB

**Comment by kjdev** [comment]
Thanks for the confirmation.
