### ISSUE TITLE
ext-snappy config.m4 AC_LANG([C++]) causes it to fail to compile inline

### ISSUE THREAD

**Issue by crazywhalecc** [kjdev/php-ext-snappy#24]
Is it better to use `AC_LANG_PUSH` and `AC_LANG_POP` when compiling related C++ files?

Because I was trying to add the snappy extension to [static-php-cli](https://github.com/crazywhalecc/static-php-cli) and discovered that the snappy extension's `AC_LANG([C++])` would cause other extensions and autoconf AC_CHECK_LIB to generate incorrect results when compiled inline.

A reproducible example is that when I was compiling Swoole and snappy inline on the macOS platform, I found that the content of conftest.c for checking kqueue in `php-src/configure` changed to `namespace conftest{`.

**Comment by kjdev** [comment]
https://github.com/kjdev/php-ext-snappy/commit/ab8b2b7375641f47deb21d8e8ba1a00ea5364cf6

I tried to fix it, Is this correct?

**Comment by crazywhalecc** [comment]
It seems to be working fine so far, thank you !
